spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/cars/**
  application:
    name: gateway-service
server:
  port: 8888
